[project]
name = "intervalo-de-confianca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.0",
    "odfpy>=1.4.1",
    "pandas>=2.3.0",
    "scipy>=1.15.3",
]
